### PR TITLE
Mothur: replacing datatypes

### PR DESCRIPTION
**Pull request by yhoogstrate**
Using

```
sed -r -i.bak 's/(format=[^ ]{0,})([,"])otu([,"])/\1\2mothur.otu\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])list([,"])/\1\2mothur.list\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])sabund([,"])/\1\2mothur.sabund\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])rabund([,"])/\1\2mothur.rabund\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])shared([,"])/\1\2mothur.shared\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])relabund([,"])/\1\2mothur.relabund\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])names([,"])/\1\2mothur.names\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])design([,"])/\1\2mothur.design\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])summary([,"])/\1\2mothur.summary\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])groups([,"])/\1\2mothur.groups\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])oligos([,"])/\1\2mothur.oligos\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])align([,"])/\1\2mothur.align\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])accnos([,"])/\1\2mothur.accnos\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])otulabels([,"])/\1\2mothur.otulabels\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])otu.corr([,"])/\1\2mothur.otu.corr\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])map([,"])/\1\2mothur.map\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])align.check([,"])/\1\2mothur.align.check\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])align.report([,"])/\1\2mothur.align.report\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])filter([,"])/\1\2mothur.filter\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])dist([,"])/\1\2mothur.dist\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])pair.dist([,"])/\1\2mothur.pair.dist\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])square.dist([,"])/\1\2mothur.square.dist\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])lower.dist([,"])/\1\2mothur.lower.dist\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])ref.taxonomy([,"])/\1\2mothur.ref.taxonomy\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])seq.taxonomy([,"])/\1\2mothur.seq.taxonomy\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])rdp.taxonomy([,"])/\1\2mothur.rdp.taxonomy\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])cons.taxonomy([,"])/\1\2mothur.cons.taxonomy\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])tax.summary([,"])/\1\2mothur.tax.summary\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])freq([,"])/\1\2mothur.freq\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])quan([,"])/\1\2mothur.quan\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])filtered.quan([,"])/\1\2mothur.filtered.quan\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])masked.quan([,"])/\1\2mothur.masked.quan\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])filtered.masked.quan([,"])/\1\2mothur.filtered.masked.quan\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])axes([,"])/\1\2mothur.axes\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])sff.flow([,"])/\1\2mothur.sff.flow\3/' *.xml
sed -r -i.bak 's/(format=[^ ]{0,})([,"])count_table([,"])/\1\2mothur.count_table\3/' *.xml

mkdir bak ; mv *.bak bak
```

### CODE REVIEW

**Comment by shiltemann** [comment]
`list` is toch wel ook een mothur datatype (tweede uit lijstje) ..kunje die nog toevoegen aan je superregex? ;)

**Comment by shiltemann** [comment]
and thanks a bunch for your help btw eh :) ..makes me feel like there might one day come a time that I'm not still working on this ;P

**Comment by yhoogstrate** [comment]
@shiltemann I've seen some `qual` type files too, do they need to be mothur.qual?

**Comment by shiltemann** [comment]
@yhoogstrate no, that's a file format that comes from 454 sequencers and not specific to mothur, so you can leave that without the prefix

**Comment by shiltemann** [comment]
looks great, thanks!

**Pull request merged**
